Document: libspotify
Title: Debian libspotify Manual
Author: <insert document author here>
Abstract: This manual describes what libspotify is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libspotify/libspotify.sgml.gz

Format: postscript
Files: /usr/share/doc/libspotify/libspotify.ps.gz

Format: text
Files: /usr/share/doc/libspotify/libspotify.text.gz

Format: HTML
Index: /usr/share/doc/libspotify/html/index.html
Files: /usr/share/doc/libspotify/html/*.html
